/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programmingassignment2;

import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author timja
 */
public class guiMainDisplay extends javax.swing.JFrame {

    /**
     * Creates new form displayWindow
     */
    
    //create customer variables and arrays
    int selectedCustomer;
    guiCustomer displayCustomer = new guiCustomer(this);
    ArrayList<guiCustomerInformation> displayCustomerInformation = new ArrayList<guiCustomerInformation>();
    public String[] getCustomerName = new String[20];
    public String[] getCustomerAddress = new String[20];
    public String[] getCustomerEmail = new String[20];
    public String[] getCustomerPhoneNumber = new String[20];
    public float[] getCustomerAmountSpent = new float[20];
    public String[] getCustomerAmountSpentFormatted = new String[20];
    public String[] getCustomerDate = new String[20];
    
    //create item variables and arrays
    int selectedItem;
    guiItem displayItem = new guiItem(this);
    ArrayList<guiItemInformation> displayItemInformation = new ArrayList<guiItemInformation>();
    public DefaultListModel itemListModel = new DefaultListModel();
    public String[] getItemName = new String[20];
    public String[] getItemID = new String[20];
    public String[] getItemSupplier = new String[20];
    public String[] getItemSerialNumber = new String[20];
    public float[] getItemCostPerItem = new float[20];
    public String[] getItemCostPerItemFormatted = new String[20];
    public float[] itemCost = new float[20];
    
    //create array to check if information window is created
    public int[] testCreated = new int[20];
    
    //create sold object to store statistics
    sold sold = new sold();
    
    public guiMainDisplay() { //main constructor
        initComponents();
        setIcon();
    }

    //post data methods
    public void postDataCustomer(){
        this.jTextFieldTotalCustomers.setText(""+this.sold.totalCustomers);
        //this.jListCustomers.setModel(a);
    }
    
    public void postDataItem(){
        this.jTextFieldTotalItems.setText(""+this.sold.totalItems);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCustomersTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListCustomers = new javax.swing.JList<>();
        jPanelItemsTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListItem = new javax.swing.JList<>();
        jPanelSaleTab = new javax.swing.JPanel();
        jLabelRawIncome = new javax.swing.JLabel();
        jLabelItemsSold = new javax.swing.JLabel();
        jLabelItemTypes = new javax.swing.JLabel();
        jLabelCustomers = new javax.swing.JLabel();
        jTextFieldRawIncome = new javax.swing.JTextField();
        jTextFieldTotalQtySold = new javax.swing.JTextField();
        jTextFieldTotalItems = new javax.swing.JTextField();
        jTextFieldTotalCustomers = new javax.swing.JTextField();
        jButtonRefresh = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonLoadCustomer = new javax.swing.JButton();
        jButtonLoadItem = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar = new javax.swing.JMenuBar();
        createJMenu = new javax.swing.JMenu();
        customerMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemMenuItem = new javax.swing.JMenuItem();
        helpJMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TheGoodGals Client Management System");
        setIconImages(null);
        setLocation(new java.awt.Point(0, 0));

        jPanelCustomersTab.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customers", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jListCustomers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jListCustomers);

        javax.swing.GroupLayout jPanelCustomersTabLayout = new javax.swing.GroupLayout(jPanelCustomersTab);
        jPanelCustomersTab.setLayout(jPanelCustomersTabLayout);
        jPanelCustomersTabLayout.setHorizontalGroup(
            jPanelCustomersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomersTabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCustomersTabLayout.setVerticalGroup(
            jPanelCustomersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomersTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addGap(1, 1, 1))
        );

        jPanelItemsTab.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Items", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jListItem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListItem);

        javax.swing.GroupLayout jPanelItemsTabLayout = new javax.swing.GroupLayout(jPanelItemsTab);
        jPanelItemsTab.setLayout(jPanelItemsTabLayout);
        jPanelItemsTabLayout.setHorizontalGroup(
            jPanelItemsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItemsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        jPanelItemsTabLayout.setVerticalGroup(
            jPanelItemsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItemsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );

        jPanelSaleTab.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sale Statistics", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabelRawIncome.setText("Total Raw Income:");

        jLabelItemsSold.setText("Total Qty of Items Sold:");

        jLabelItemTypes.setText("Total Types of Items:");

        jLabelCustomers.setText("Total Customers:");

        jTextFieldRawIncome.setEditable(false);
        jTextFieldRawIncome.setText("$0.00");
        jTextFieldRawIncome.setToolTipText("Raw Income");
        jTextFieldRawIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRawIncomeActionPerformed(evt);
            }
        });

        jTextFieldTotalQtySold.setEditable(false);
        jTextFieldTotalQtySold.setText("0");
        jTextFieldTotalQtySold.setToolTipText("Item Sold");

        jTextFieldTotalItems.setEditable(false);
        jTextFieldTotalItems.setText("0");
        jTextFieldTotalItems.setToolTipText("Total Item Types");

        jTextFieldTotalCustomers.setEditable(false);
        jTextFieldTotalCustomers.setText("0");
        jTextFieldTotalCustomers.setToolTipText("Total Customers");
        jTextFieldTotalCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalCustomersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSaleTabLayout = new javax.swing.GroupLayout(jPanelSaleTab);
        jPanelSaleTab.setLayout(jPanelSaleTabLayout);
        jPanelSaleTabLayout.setHorizontalGroup(
            jPanelSaleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaleTabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelSaleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRawIncome)
                    .addComponent(jLabelItemsSold)
                    .addComponent(jLabelItemTypes)
                    .addComponent(jLabelCustomers))
                .addGap(18, 18, 18)
                .addGroup(jPanelSaleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTotalCustomers)
                    .addComponent(jTextFieldTotalItems)
                    .addComponent(jTextFieldRawIncome, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jTextFieldTotalQtySold, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelSaleTabLayout.setVerticalGroup(
            jPanelSaleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaleTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSaleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRawIncome)
                    .addComponent(jTextFieldRawIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSaleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelItemsSold)
                    .addComponent(jTextFieldTotalQtySold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSaleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelItemTypes)
                    .addComponent(jTextFieldTotalItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSaleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCustomers)
                    .addComponent(jTextFieldTotalCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonRefresh.setText("Refresh Stats");
        jButtonRefresh.setToolTipText("Refresh Statistics");
        jButtonRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.setToolTipText("Exit Program");
        jButtonExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonLoadCustomer.setText("Load Customer Info");
        jButtonLoadCustomer.setToolTipText("Load Selected Customer Info");
        jButtonLoadCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLoadCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadCustomerActionPerformed(evt);
            }
        });

        jButtonLoadItem.setText("Load Item Info");
        jButtonLoadItem.setToolTipText("Load Selected Item Info");
        jButtonLoadItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLoadItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadItemActionPerformed(evt);
            }
        });

        createJMenu.setText("Create");
        createJMenu.setToolTipText("Create Objects");
        createJMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        customerMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        customerMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programmingassignment2/icons/iconCustomer.png"))); // NOI18N
        customerMenuItem.setText("Customer");
        customerMenuItem.setToolTipText("Create Customer");
        customerMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerMenuItemActionPerformed(evt);
            }
        });
        createJMenu.add(customerMenuItem);
        createJMenu.add(jSeparator1);

        itemMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK));
        itemMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programmingassignment2/icons/iconShopping.png"))); // NOI18N
        itemMenuItem.setText("Item");
        itemMenuItem.setToolTipText("Create Items");
        itemMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuItemActionPerformed(evt);
            }
        });
        createJMenu.add(itemMenuItem);

        jMenuBar.add(createJMenu);

        helpJMenu.setText("Help");
        helpJMenu.setToolTipText("Help");
        helpJMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK));
        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programmingassignment2/icons/iconHelp.png"))); // NOI18N
        aboutMenuItem.setText("About");
        aboutMenuItem.setToolTipText("More Info");
        aboutMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpJMenu.add(aboutMenuItem);

        jMenuBar.add(helpJMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelCustomersTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelItemsTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSaleTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLoadCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLoadItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelCustomersTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelItemsTab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanelSaleTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLoadCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLoadItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRefresh)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExit)))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRawIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRawIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRawIncomeActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        //create help window
        guiHelp displayHelp = new guiHelp();
        displayHelp.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void customerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerMenuItemActionPerformed
        //set customer display to visible
        displayCustomer.setVisible(true);
    }//GEN-LAST:event_customerMenuItemActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
             System.exit(0); //exit system
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jTextFieldTotalCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalCustomersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalCustomersActionPerformed

    private void itemMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuItemActionPerformed
        //set item display to visible
        displayItem.setVisible(true);
    }//GEN-LAST:event_itemMenuItemActionPerformed

    private void jButtonLoadCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadCustomerActionPerformed
        //get selected customer in list
        selectedCustomer = jListCustomers.getSelectedIndex();
        
        //check if gui has been created
        if (testCreated[selectedCustomer] == 0){
        
            //send information to customer information
            displayCustomerInformation.add(new guiCustomerInformation(this));
            displayCustomerInformation.get(selectedCustomer).jPanelCustomerName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer "+selectedCustomer+" Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
            displayCustomerInformation.get(selectedCustomer).jTextFieldName.setText(getCustomerName[selectedCustomer]);
            displayCustomerInformation.get(selectedCustomer).jTextFieldAddress.setText(getCustomerAddress[selectedCustomer]);
            displayCustomerInformation.get(selectedCustomer).jTextFieldEmail.setText(getCustomerEmail[selectedCustomer]);
            displayCustomerInformation.get(selectedCustomer).jTextFieldPhoneNumber.setText(getCustomerPhoneNumber[selectedCustomer]);
            displayCustomerInformation.get(selectedCustomer).jTextFieldAmountSpent.setText(getCustomerAmountSpentFormatted[selectedCustomer]);
            displayCustomerInformation.get(selectedCustomer).jTextFieldDate.setText(getCustomerDate[selectedCustomer]);
            //set model for purchases
            displayCustomerInformation.get(selectedCustomer).itemCost = itemCost;
            displayCustomerInformation.get(selectedCustomer).jListItem.setModel(itemListModel);
            displayCustomerInformation.get(selectedCustomer).setVisible(true);       
            //set test created to 1
            testCreated[selectedCustomer] = 1;        
        }
        
        else {
            //update model for purchases
            displayCustomerInformation.get(selectedCustomer).itemCost = itemCost;
            displayCustomerInformation.get(selectedCustomer).jListItem.setModel(itemListModel);    
            displayCustomerInformation.get(selectedCustomer).setVisible(true);
        }
    }//GEN-LAST:event_jButtonLoadCustomerActionPerformed

    private void jButtonLoadItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadItemActionPerformed
        //get selected customer in list
        selectedItem = jListItem.getSelectedIndex();
        displayItemInformation.add(new guiItemInformation());
        //send information to customer information
        displayItemInformation.get(selectedItem).jPanelItemName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Item "+selectedItem+" Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        displayItemInformation.get(selectedItem).jTextFieldName.setText(getItemName[selectedItem]);
        displayItemInformation.get(selectedItem).jTextFieldID.setText(getItemID[selectedItem]);
        displayItemInformation.get(selectedItem).jTextFieldSerialNumber.setText(getItemSerialNumber[selectedItem]);
        displayItemInformation.get(selectedItem).jTextFieldName.setText(getItemName[selectedItem]);
        displayItemInformation.get(selectedItem).jTextFieldSupplier.setText(getItemSupplier[selectedItem]);
        displayItemInformation.get(selectedItem).jTextFieldIndividualCost.setText(getItemCostPerItemFormatted[selectedItem]);
        //set visible
        displayItemInformation.get(selectedItem).setVisible(true);
    }//GEN-LAST:event_jButtonLoadItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiMainDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiMainDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiMainDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiMainDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiMainDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenu createJMenu;
    private javax.swing.JMenuItem customerMenuItem;
    private javax.swing.JMenu helpJMenu;
    private javax.swing.JMenuItem itemMenuItem;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonLoadCustomer;
    private javax.swing.JButton jButtonLoadItem;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabelCustomers;
    private javax.swing.JLabel jLabelItemTypes;
    private javax.swing.JLabel jLabelItemsSold;
    private javax.swing.JLabel jLabelRawIncome;
    public javax.swing.JList<String> jListCustomers;
    public javax.swing.JList<String> jListItem;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanelCustomersTab;
    private javax.swing.JPanel jPanelItemsTab;
    private javax.swing.JPanel jPanelSaleTab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField jTextFieldRawIncome;
    public javax.swing.JTextField jTextFieldTotalCustomers;
    public javax.swing.JTextField jTextFieldTotalItems;
    public javax.swing.JTextField jTextFieldTotalQtySold;
    // End of variables declaration//GEN-END:variables
    //set window icon constructor
    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/programmingassignment2/icons/iconGoodGalsLogo.png")));
    }
}